tasks:
  - init: mvn install -DskipTests=false
image:
  file: .gitpod.Dockerfile
<<<<<<< HEAD
=======

vscode:
  extensions:
    - formulahendry.code-runner@0.9.15:WUpvbF4Wg44WiaFa7exZBw==
>>>>>>> origin/moxingwang/gitpod-setup
